### PR TITLE
Implementation for showing/hiding attributes

### PR DESCRIPTION
**Pull request by IIStevowII**
I've taken the liberty to add functionality to hide certain attributes, including using the UI editor.
I really love the plug-in but am not really interested in information like wind and visibility, so I would rather hide them to make the card compacter.

I'm new to HA and the lovelace editor, so i'm sorry if I didn't use any preffered conventions. I've tried to use as much as possible like existing code/syntax/style.

I would love to hear if certain things are not (yet) good enough, but hope you like the improvement.

### CODE REVIEW

**Comment by IIStevowII** [comment]
It is unclear for me what the exact usage/difference is between Readme.md and info.md, so i've added the new instructions to both.

**Comment by bramkragten** [comment]
Yes, HACS uses `info.md`

**Comment by damienclaveau** [comment]
+1 
I also really love the plug-in.
And as a HA user, I often look in the custom components for more flexibility.
Some weather platforms don't offer all the attributes the darksky does, so I would be happy to hide these missing ones.

**Comment by sverleysen** [comment]
@IIStevowII can you please revert the asked changes? I'm really looking forward on seeing this PR being merged.

**Comment by IIStevowII** [comment]
@sverleysen Sorry this PR took way too long and there are too many differences now, it seems that @bramkragten also implemented some toggles himself in the meanwhile. I tried to rebase and figure everything out but I can't. There are just too many changes.

I don't have a Home Assistant setup currently and can't check for things, so I'm going to discard this PR. Feel free to pick this up yourself if you want to.

**Pull request closed without merging**
